name: Uruchom Testy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v2

    - name: Skonfiguruj Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Zainstaluj zależności
      run: |
        pip install -r requirements.txt

    - name: Uruchom testy
      run: pytest
