name: Test python files
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check repo
      uses: actions/checkout@v2
    - name: Python set up
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
